version: "3.8"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
    - 27017:${DB_PORT}
    
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongoexpress
    ports:
    - 8081:${DB_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${DB_PORT}/
    